services:
  pebackend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pebackend
    restart: unless-stopped

    ports:
      - "444:444"

    environment:
      API_HOST: "192.168.1.118"
      API_PORT: "444"
      MONGO_URI: "${MONGO_URI}"
      MONGO_DB: "${MONGO_DB}"
      JWT_SECRET: "${JWT_SECRET}"