services:
  pebackend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pebackend
    restart: unless-stopped

    ports:
      - "443:443"

    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "443"
      MONGO_URI: "${MONGO_URI}"
      MONGO_DB: "${MONGO_DB}"
      JWT_SECRET: "${JWT_SECRET}"